model:
  base_learning_rate: 4.5e-6
  target: vqgan.VQModel
  params:
    ckpt_path: vqgan_f8.ckpt
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig: None

data:
  params:
    batch_size: 8
    num_workers: 12
    train:
      target: dataset.CustomTrain
      params:
        training_images_list_file: chexpert.txt
        size: 256
    validation:
      target: dataset.CustomTest
      params:
        test_images_list_file: chexpert.txt
        size: 256


